export const data = [
  {
    id: 0,
    key: "item0",
    name: "Notebook 13",
    req_units: 205,
    weight: 2451,
    utility: 40,
    img: "/images/note13.png",
  },
  {
    id: 1,
    key: "item1",
    name: "Notebook 14",
    req_units: 420,
    weight: 2978,
    utility: 35,
    img: "/images/note14.png",
  },
  {
    id: 2,
    key: "item2",
    name: "Notebook Outdoor",
    req_units: 450,
    weight: 3625,
    utility: 80,
    img: "/images/notebook_outdoor.png",
  },
  {
    id: 3,
    key: "item3",
    name: "Mobiltelefon Büro",
    req_units: 60,
    weight: 717,
    utility: 30,
    img: "/images/phone_office.png",
  },
  {
    id: 4,
    key: "item4",
    name: "Mobiltelefon Outdoor",
    req_units: 157,
    weight: 988,
    utility: 60,
    img: "/images/phone_outdoor.png",
  },
  {
    id: 5,
    key: "item5",
    name: "Mobiltelefon Heavy",
    req_units: 220,
    weight: 1220,
    utility: 65,
    img: "/images/phone_heavy.png",
  },
  {
    id: 6,
    key: "item6",
    name: "Tablet Büro klein",
    req_units: 620,
    weight: 1405,
    utility: 40,
    img: "/images/tablet_small.png",
  },
  {
    id: 7,
    key: "item7",
    name: "Tablet Büro groß",
    req_units: 250,
    weight: 1455,
    utility: 40,
    img: "/images/tablet_big.png",
  },
  {
    id: 8,
    key: "item8",
    name: "Tablet Outdoor klein",
    req_units: 540,
    weight: 1690,
    utility: 45,
    img: "/images/tablet_outdoor_small.png",
  },
  {
    id: 9,
    key: "item9",
    name: "Tablet Outdoor groß",
    req_units: 370,
    weight: 1980,
    utility: 68,
    img: "/images/tablet_outdoor_big.png",
  },
];

export const columns = [
  { field: "id", headerName: "ID", width: 50 },
  { field: "name", headerName: "Hardware", width: 150 },
  {
    field: "req_units",
    headerName: "Needed req_units",
    type: "number",
    width: 120,
  },
  {
    field: "weight",
    headerName: "Weight (g)",
    type: "number",
    width: 120,
  },
  {
    field: "utility",
    headerName: "Utility (^)",
    type: "number",
    width: 120,
  },
  {
    field: "ratio1",
    headerName: "weight/utility ratio",
    description: "",
    sortable: false,
    width: 150,
    valueGetter: (params) =>
      `${parseFloat(
        params.getValue("weight") / params.getValue("utility")
      ).toFixed(3)}`,
  },
  {
    field: "ratio2",
    headerName: "utility/weight ratio",
    description: "",
    sortable: false,
    width: 150,
    valueGetter: (params) =>
      `${parseFloat(
        params.getValue("utility") / params.getValue("weight")
      ).toFixed(3)}`,
  },
];

export const baseline = [
  {
    id: 0,
    name: "Transporter 1",
    add_weight: 1100000,
    driver: 72400,
    weight_left: 1027600,
    items: [],
    utility_sum: 0,
    weight_sum: 0,
    img: "/images/transporter1.png",
  },
  {
    id: 1,
    name: "Transporter 2",
    add_weight: 1100000,
    driver: 85700,
    weight_left: 1014300,
    items: [],
    utility_sum: 0,
    weight_sum: 0,
    img:"/images/transporter2.png",
  },
];
